-- Sports EV Engine v3.2 persistent history table.
-- Run once in Supabase SQL Editor, then store SUPABASE_URL and
-- SUPABASE_SERVICE_ROLE_KEY only in Streamlit secrets / server environment.

create table if not exists public.sports_ev_records (
  id bigint generated by default as identity primary key,
  kind text not null,
  record_id text not null,
  event_id text,
  sport_key text,
  commence_time timestamptz,
  created_at timestamptz not null default now(),
  payload jsonb not null,
  unique (kind, record_id)
);

create index if not exists sports_ev_records_kind_created_idx
  on public.sports_ev_records(kind, created_at desc);
create index if not exists sports_ev_records_event_idx
  on public.sports_ev_records(event_id, kind);
create index if not exists sports_ev_records_sport_time_idx
  on public.sports_ev_records(sport_key, commence_time);

alter table public.sports_ev_records enable row level security;
-- No public RLS policy is intentionally created. The service-role key bypasses
-- RLS. Never put that key in source code or expose it to browser JS.
